services:
  mysql:
    image: mysql:8.0
    container_name: minitms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: masterdata
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecret"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: minitms-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data